## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build
        run: ./mvnw -DskipTests package -B

      - name: Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/*

  maven-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build
        run: ./mvnw test -B

  maven-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build
        run: ./mvnw verify -B

  docker:
    runs-on: ubuntu-latest
    needs: [maven-build, maven-unit, maven-it]
    steps:
      - uses: actions/checkout@v4

      - name: Artefakt herunterladen
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: target/

      - name: Docker Build
        run: docker build -f src/main/docker/Dockerfile.jvm -t ghcr.io/ffaarno/code-with-quarkus:${{ github.sha }} .

      - name: Docker Login
        run: echo ${{ secrets.ACTION_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker Push
        run: |
          docker push ghcr.io/ffaarno/code-with-quarkus:${{ github.sha }}
          docker tag ghcr.io/ffaarno/code-with-quarkus:${{ github.sha }} ghcr.io/ffaarno/code-with-quarkus:latest
          docker push ghcr.io/ffaarno/code-with-quarkus:latest